import { QuizPlayer, type QuizItem } from "../_digestive/players";

const items: QuizItem[] = [
  // ---------------- Endoscopy rules ----------------
  {
    topic: "Endoscopy rules",
    question: "During an EGD the doctor finds a duodenal ulcer and takes two biopsies. What is reported?",
    correct: "43239",
    wrong: ["43235, 43239", "43239 twice, once per biopsy", "43235"],
    explanation: "43239 is EGD 'with biopsy, single or multiple'. A therapeutic scope already includes the diagnostic look, and the code covers one OR many biopsies.",
    lookFor: "The doctor DID something (a biopsy), so only the therapeutic code is reported.",
    eliminate: "Adding 43235 double-counts the look. Reporting 43239 twice ignores 'single or multiple'. 43235 alone leaves out the biopsy.",
  },
  {
    topic: "Endoscopy rules",
    question: "During a colonoscopy a polyp is removed with a snare. The polyp site oozes afterward and the doctor places clips to stop it. What is reported?",
    correct: "45385 only",
    wrong: ["45385, 45382", "45385, 45382-59", "45382 only"],
    explanation: "Bleeding that is caused by the endoscopic procedure itself, and controlled in the same session, is packaged and not reported separately.",
    lookFor: "Ask WHY there was bleeding. A bleeding lesion that was the reason for the scope is different from bleeding caused by the scope.",
    eliminate: "Modifier 59 cannot unpack a service the rules say is packaged. 45382 alone drops the polyp removal.",
  },
  {
    topic: "Endoscopy rules",
    question: "A doctor passes a scope through the mouth and examines the esophagus, stomach, and duodenum, plus about 20 cm beyond the pylorus. Which code family is this?",
    correct: "EGD, 43235–43259",
    wrong: ["Enteroscopy to the jejunum, 44360–44373", "Flexible esophagoscopy, 43200–43232", "Enteroscopy to the ileum, 44376–44379"],
    explanation: "Reach less than 50 cm past the pylorus stays in the EGD family. 50 cm or more moves you to enteroscopy.",
    lookFor: "The 50 cm line past the pylorus is the whole EGD-versus-enteroscopy decision.",
    eliminate: "Both enteroscopy families need 50 cm or more past the pylorus. Esophagoscopy stops at the GE junction.",
  },

  // ---------------- Esophagoscopy ----------------
  {
    topic: "Esophagoscopy",
    question: "A thin flexible scope is passed through the patient's nose to look at the esophagus. Nothing is biopsied or treated. Which code?",
    correct: "43197",
    wrong: ["43191", "43200", "43235"],
    explanation: "43197 is the diagnostic flexible TRANSNASAL esophagoscopy.",
    lookFor: "Two words decide it: flexible and transnasal (through the nose).",
    eliminate: "43191 is rigid. 43200 is flexible transoral (through the mouth). 43235 is an EGD, which reaches the stomach and duodenum.",
  },
  {
    topic: "Esophagoscopy",
    question: "Flexible transoral esophagoscopy with dilation of a stricture using a 32 mm balloon. Fluoroscopic guidance was used. Which code(s)?",
    correct: "43214",
    wrong: ["43214, 74360", "43213, 74360", "43220, 74360"],
    explanation: "43214 is balloon dilation of 30 mm or larger, and it already includes fluoroscopic guidance when performed. 74360 is not added to it.",
    lookFor: "The balloon size (30 mm or more) and the phrase 'includes fluoroscopic guidance'.",
    eliminate: "Any answer that adds 74360 is wrong because 43213 and 43214 already include the fluoroscopy. 43220 is a balloon under 30 mm.",
  },
  {
    topic: "Esophagoscopy",
    question: "A doctor uses a RIGID esophagoscope through the mouth to remove a coin the patient swallowed. Which code?",
    correct: "43194",
    wrong: ["43191, 43194", "43215", "43247"],
    explanation: "43194 is rigid transoral esophagoscopy with removal of a foreign body. The diagnostic code 43191 is not added.",
    lookFor: "Rigid scope + foreign body. Then check the family: esophagus only.",
    eliminate: "43191 is not reported with 43194. 43215 is the flexible version. 43247 is the EGD version.",
  },

  // ---------------- EGD ----------------
  {
    topic: "EGD",
    question: "A patient with severe gastric retention has an EGD. The scope cannot pass the pylorus, so the duodenum is not examined. The doctor biopsies the stomach lining. No repeat exam is planned. Which code?",
    correct: "43239-52",
    wrong: ["43239-53", "43235-52", "43239"],
    explanation: "Biopsy makes it the therapeutic code 43239. The duodenum was not reached and no repeat exam is planned, so the reduced-service modifier 52 is added.",
    lookFor: "Two checkpoints: was the duodenum reached, and is a repeat exam planned?",
    eliminate: "53 is for the case where a repeat exam IS planned. 43235 drops the biopsy. Leaving off the modifier hides that the exam fell short.",
  },
  {
    topic: "EGD",
    question: "A diagnostic EGD is stopped in the stomach and the duodenum is not examined. The doctor plans to repeat the exam next week. Which code?",
    correct: "43235-53",
    wrong: ["43235-52", "43200", "43235"],
    explanation: "For an EGD that skips the duodenum, modifier 52 means no repeat exam is planned and modifier 53 means a repeat IS planned. Nothing was done besides looking, so the base code 43235 applies.",
    lookFor: "The words 'repeat planned'. They flip 52 to 53.",
    eliminate: "52 is for no repeat. 43200 is an esophagoscopy code, but the stomach was examined. Without a modifier the shortened exam is invisible.",
  },
  {
    topic: "EGD",
    question: "EGD with band ligation of esophageal varices. Which code?",
    correct: "43244",
    wrong: ["43243", "43205", "43236"],
    explanation: "43244 is EGD with band ligation of esophageal/gastric varices. For varices the variceal codes are used, not the general injection or band codes.",
    lookFor: "Varices plus the technique. Injection sclerosis is one code, banding is the next.",
    eliminate: "43243 is sclerosis injection of varices. 43205 belongs to the esophagoscopy family. 43236 is a general submucosal injection.",
  },
  {
    topic: "EGD",
    question: "EGD with balloon dilation of a stricture at the gastric outlet (the pylorus). Which code?",
    correct: "43245",
    wrong: ["43249", "43233", "43248"],
    explanation: "43245 is EGD with dilation of a gastric or duodenal stricture. 43233, 43248, and 43249 are the esophageal dilation codes.",
    lookFor: "WHERE is the stricture? Esophagus versus stomach or duodenum.",
    eliminate: "43249 and 43233 are balloon dilations of the esophagus by size. 43248 is guidewire dilation of the esophagus.",
  },
  {
    topic: "EGD",
    question: "A patient with a prior gastric bypass has a scope passed through the mouth. The doctor examines the pouch and the jejunum just past the surgical join. Which family?",
    correct: "43235, EGD family",
    wrong: ["44360, enteroscopy", "44376, enteroscopy to the ileum", "44799, unlisted intestine procedure"],
    explanation: "On a surgically altered stomach, examining the jejunum just past the connection still uses the EGD codes.",
    lookFor: "'Altered stomach' plus a short reach beyond the join. It does not automatically become enteroscopy.",
    eliminate: "The enteroscopy codes need 50 cm or more of small bowel past the pylorus. 44799 is for retrograde small-bowel exams.",
  },

  // ---------------- Enteroscopy ----------------
  {
    topic: "Enteroscopy",
    question: "A scope is passed through the mouth and advanced about 90 cm past the pylorus into the jejunum. The doctor biopsies the jejunum. Which code?",
    correct: "44361",
    wrong: ["43239", "44377", "44360, 44361"],
    explanation: "50 cm or more past the pylorus, ending in the jejunum, is the 44360–44373 family. Biopsy is 44361, and the diagnostic 44360 is not added.",
    lookFor: "The reach (past 50 cm) and the farthest segment (jejunum, not ileum).",
    eliminate: "43239 is an EGD biopsy. 44377 is the ileum biopsy. Adding 44360 double-counts the look.",
  },
  {
    topic: "Enteroscopy",
    question: "A doctor passes a scope through an ileostomy stoma and looks at the ileum. Nothing else is done. Which code?",
    correct: "44380",
    wrong: ["44388", "44376", "44799"],
    explanation: "44380 is diagnostic ileoscopy through a stoma.",
    lookFor: "Ileum plus 'through a stoma'.",
    eliminate: "44388 is a colonoscopy through a stoma. 44376 is antegrade enteroscopy through the ileum. 44799 is for retrograde small-bowel exams by the anus or a colon stoma.",
  },

  // ---------------- ERCP ----------------
  {
    topic: "ERCP",
    question: "During an ERCP the doctor cannulates the bile duct and images it, but cannot cannulate the pancreatic duct. Nothing else is done. Which code?",
    correct: "43260",
    wrong: ["43235", "43260-52", "43260-53"],
    explanation: "An ERCP is complete if at least ONE ductal system is visualized. The bile duct was, so 43260 stands with no modifier.",
    lookFor: "How many duct systems were visualized. One is enough.",
    eliminate: "An EGD code is only for the case where NO duct was visualized. 52 and 53 are not needed for a complete ERCP.",
  },
  {
    topic: "ERCP",
    question: "ERCP with sphincterotomy and removal of bile duct stones. Which code(s)?",
    correct: "43262, 43264",
    wrong: ["43264", "43262, 43277", "43260, 43264"],
    explanation: "43262 may be reported together with 43264 when the papilla is cut in addition to clearing the stones. The diagnostic 43260 is never added.",
    lookFor: "Two distinct steps: cutting the papilla and clearing stones.",
    eliminate: "43264 alone drops the cut. 43277 is the stretching (balloon) code and cannot be paired with 43262. 43260 is packaged.",
  },
  {
    topic: "ERCP",
    question: "During one ERCP the doctor places a stent in the common bile duct and a second stent in the pancreatic duct. Which code(s)?",
    correct: "43274, 43274-59",
    wrong: ["43274, 43274", "43274, 43274-50", "43274-59, 43274-59"],
    explanation: "43274 is counted per stent. The stents sit in two different ducts, so the second stent gets modifier 59.",
    lookFor: "Stents in separate ducts. That is what earns the modifier 59.",
    eliminate: "Repeating a code without a modifier gets denied as a duplicate. 50 means both sides of the body. 59 on the first line has nothing to be distinct from.",
  },
  {
    topic: "ERCP",
    question: "During one ERCP the doctor removes two old stents from the bile duct and places nothing new. What is reported?",
    correct: "43275 once",
    wrong: ["43275, 43275-59", "43276, 43276-59", "43275 twice with modifier 51"],
    explanation: "43275 is reported ONCE per session for removal of one or more stents or foreign bodies.",
    lookFor: "The words 'one or more' in the descriptor. That makes the code a once-per-session code.",
    eliminate: "No modifier turns a once-per-session code into a per-stent code. 43276 is for removal AND exchange (replacement).",
  },
  {
    topic: "ERCP",
    question: "ERCP with balloon dilation of the ampulla (sphincteroplasty). A sphincterotomy was also done in the same session. Which code(s)?",
    correct: "43277",
    wrong: ["43262, 43277", "43262", "43277, 43274"],
    explanation: "43277 already includes the sphincterotomy, and 43262 is not reported with 43277.",
    lookFor: "The mnemonic: 43262 cuts, 43277 stretches. If both happen, only the stretch code is reported.",
    eliminate: "Listing both counts the cut twice. 43262 alone drops the dilation. 43274 needs an actual stent.",
  },
  {
    topic: "ERCP",
    question: "ERCP with sphincterotomy plus cholangioscopy (direct visualization of the common bile duct through the papilla). Which code(s)?",
    correct: "43262, +43273",
    wrong: ["43262", "43273", "43260, +43273"],
    explanation: "+43273 is an add-on for cannulation of the papilla with direct visualization, reported once per procedure with the primary ERCP code.",
    lookFor: "A plus sign means the code needs a primary code with it.",
    eliminate: "43262 alone leaves out the direct visualization. An add-on can never be reported by itself. 43260 is packaged into 43262.",
  },
  {
    topic: "ERCP",
    question: "ERCP with lithotripsy that breaks up the stones in the bile duct, then clears them out. Which code?",
    correct: "43265",
    wrong: ["43264, 43265", "43264", "43265, 43264-59"],
    explanation: "43265 is destruction of calculi by any method and includes removing the stones from the same ductal system.",
    lookFor: "Destruction versus removal. Destruction includes removal.",
    eliminate: "Adding 43264 counts removal twice. 43264 alone leaves out the lithotripsy. Modifier 59 has nothing distinct to attach to.",
  },

  // ---------------- Lower GI ----------------
  {
    topic: "Sigmoidoscopy",
    question: "A flexible sigmoidoscopy is planned to end in the descending colon. The doctor takes a biopsy. Which code?",
    correct: "45331",
    wrong: ["45330, 45331", "45380", "45305"],
    explanation: "45331 is flexible sigmoidoscopy with biopsy, single or multiple.",
    lookFor: "Flexible plus a planned reach short of the splenic flexure.",
    eliminate: "The diagnostic code is packaged. 45380 is colonoscopy. 45305 is rigid proctosigmoidoscopy.",
  },
  {
    topic: "Sigmoidoscopy",
    question: "Flexible sigmoidoscopy with rubber band ligation of internal hemorrhoids. Which code?",
    correct: "45350",
    wrong: ["46221", "45398", "46221, 45330"],
    explanation: "Band ligation through a sigmoidoscope is 45350. It is coded with the scope, not with the hemorrhoid codes.",
    lookFor: "A scope was used, so the scope code carries the band ligation.",
    eliminate: "46221 is for banding WITHOUT a scope, and it is not reported with 45350. 45398 is the colonoscopy version.",
  },
  {
    topic: "Anoscopy",
    question: "Anoscopy with removal of several polyps by snare. Which code?",
    correct: "46612",
    wrong: ["46611 for each polyp", "46610", "46611, 46611-59"],
    explanation: "Anoscopy splits a single lesion (46610, 46611) from MULTIPLE lesions (46612). Several polyps use the multiple-lesion code once.",
    lookFor: "The word 'multiple' in the descriptor of the anoscopy and rigid proctosigmoidoscopy codes.",
    eliminate: "Repeating the single-lesion code ignores the multiple-lesion code that exists. 46610 is for hot forceps or bipolar on one lesion.",
  },
  {
    topic: "Anoscopy",
    question: "High-resolution anoscopy (magnified, with chemical enhancement) with a biopsy. Which code?",
    correct: "46607",
    wrong: ["46601", "46606", "46601, 46606"],
    explanation: "46601 is diagnostic HRA. 46607 is HRA with biopsy.",
    lookFor: "'High-resolution' sends you to the HRA pair. The biopsy picks the second code.",
    eliminate: "46601 leaves out the biopsy. 46606 is standard anoscopy with biopsy. Combining them double-counts the exam.",
  },

  // ---------------- Colonoscopy ----------------
  {
    topic: "Colonoscopy",
    question: "A 40-year-old has a screening colonoscopy. Multiple small polyps are removed with a snare. What is reported?",
    correct: "45385, once",
    wrong: ["45378, 45385", "45385 for each polyp", "45380"],
    explanation: "Snare removal is 45385. The descriptor says 'polyp(s)', so one OR many polyps removed by the same technique are reported once. The diagnostic 45378 is packaged.",
    lookFor: "The removal TOOL (snare) and the '(s)' in the descriptor.",
    eliminate: "45378 double-counts the look. One code per polyp ignores '(s)'. 45380 is a biopsy, not a snare removal.",
  },
  {
    topic: "Colonoscopy",
    question: "A colonoscopy planned as a total exam stops at the descending colon because of poor prep. Nothing is biopsied or removed. Which code?",
    correct: "45378-53",
    wrong: ["45330", "45378-52", "45378"],
    explanation: "A planned total colonoscopy that stops early stays in the colonoscopy family. Looking only is the diagnostic code with modifier 53.",
    lookFor: "The PLAN decides the family. Where the scope ended up does not change it.",
    eliminate: "45330 is a sigmoidoscopy, meant to stop at the splenic flexure by design. 52 is for an incomplete THERAPEUTIC colonoscopy. No modifier hides the shortfall.",
  },
  {
    topic: "Colonoscopy",
    question: "A second patient has the same problem and the colonoscopy stops at the descending colon. But this time one polyp is removed with a snare before the doctor stops. Which code?",
    correct: "45385-52",
    wrong: ["45385-53", "45378-53, 45385", "45385"],
    explanation: "An incomplete THERAPEUTIC colonoscopy is reported with the therapeutic code and modifier 52. The diagnostic code is not added.",
    lookFor: "Was anything done? Diagnostic incomplete = 53. Therapeutic incomplete = the therapeutic code with 52.",
    eliminate: "53 is for the looking-only case. Stacking the diagnostic code double-counts. Leaving off the modifier hides the incomplete exam.",
  },
  {
    topic: "Colonoscopy",
    question: "During a colonoscopy, one polyp is removed with a snare and another with hot biopsy forceps. What is reported?",
    correct: "45385, 45384-59",
    wrong: ["45385 only", "45385, 45384", "45384, 45385, 45380"],
    explanation: "Different techniques on different lesions get their own code each. Modifier 59 goes on the additional code, following the usual payer and NCCI conventions.",
    lookFor: "Different tools, different lesions. One code per technique.",
    eliminate: "45385 alone leaves out the forceps removal. Without the modifier the second code looks like a duplicate. 45380 is a biopsy code.",
  },
  {
    topic: "Colonoscopy",
    question: "During a colonoscopy the doctor dilates two separate strictures with a balloon. Which code(s)?",
    correct: "45386, 45386-59",
    wrong: ["45386 only", "45386, 45386-50", "45386, 45386"],
    explanation: "For several strictures dilated in the same session, the dilation code is reported once, then again with modifier 59 for each additional stricture.",
    lookFor: "The note under the dilation codes about 'each additional stricture'.",
    eliminate: "A single line leaves out the second stricture. 50 means bilateral body parts. A duplicate line without a modifier is denied.",
  },
  {
    topic: "Colonoscopy",
    question: "During one colonoscopy, EUS-guided needle aspiration is done on two separate rectal lesions. How is 45392 reported?",
    correct: "Once — it is a once-per-session code",
    wrong: ["Twice, the second with modifier 59", "Twice with modifier 50", "45392 plus 45391"],
    explanation: "45392 carries a note that it is not reported more than once per session, so the number of lesions does not add a second unit.",
    lookFor: "A 'do not report more than once per session' line under the code.",
    eliminate: "Modifier 59 cannot override a once-per-session limit. 50 means bilateral. 45391 is the EUS-only code, and the two are not stacked.",
  },
  {
    topic: "Stoma endoscopy",
    question: "A colonoscopy through a colostomy stoma with a biopsy. Which code?",
    correct: "44389",
    wrong: ["45380", "44388", "44388, 44389"],
    explanation: "Colonoscopy through a stoma has its own range, 44388–44408. 44389 is with biopsy, and the diagnostic 44388 is not reported with it.",
    lookFor: "The route: through the rectum or through a stoma.",
    eliminate: "45380 is the rectal-route biopsy. 44388 alone leaves out the biopsy, and stacking it double-counts the look.",
  },

  // ---------------- Bariatric ----------------
  {
    topic: "Bariatric",
    question: "A laparoscopic Roux-en-Y gastric bypass with a 120 cm Roux limb. Which code?",
    correct: "43644",
    wrong: ["43645", "43846", "43775"],
    explanation: "Laparoscopic bypass with a Roux limb of 150 cm or less is 43644.",
    lookFor: "Approach (laparoscopic) and limb length (150 cm or less).",
    eliminate: "43645 is more than 150 cm or small-intestine reconstruction. 43846 is the open bypass. 43775 is a sleeve gastrectomy.",
  },
  {
    topic: "Bariatric",
    question: "An OPEN sleeve gastrectomy (no bypass) for obesity. Which code?",
    correct: "43843",
    wrong: ["43775", "43644", "43846"],
    explanation: "An open gastric restriction without bypass, other than vertical banded gastroplasty, is 43843. 43775 is the laparoscopic sleeve.",
    lookFor: "Same operation, different approach. The approach picks the code.",
    eliminate: "43775 is the laparoscopic sleeve. 43644 and 43846 are bypass codes.",
  },
  {
    topic: "Bariatric",
    question: "Laparoscopic removal and replacement of BOTH the gastric band and the port. Which code?",
    correct: "43659",
    wrong: ["43773", "43774, 43770", "43772, 43770"],
    explanation: "There is no dedicated code for removing and replacing both components. It goes to the unlisted laparoscopy stomach code, 43659. 43773 covers only a single component.",
    lookFor: "The table row 'REPLACE, both band and port'.",
    eliminate: "43773 is for ONE component. The stacked answers put together codes the codebook does not pair for this service.",
  },
  {
    topic: "Bariatric",
    question: "Open biliopancreatic diversion with duodenal switch, leaving a 75 cm common channel. Which code?",
    correct: "43845",
    wrong: ["43847", "43846", "43633"],
    explanation: "43845 is BPD-DS: partial gastrectomy, pylorus-preserving duodenoileostomy, and ileoileostomy with a 50–100 cm common channel.",
    lookFor: "'Duodenal switch' and 'common channel' point to 43845.",
    eliminate: "43846 and 43847 are open gastric bypass codes. 43633 is a distal gastrectomy with Roux-en-Y reconstruction, not the duodenal switch.",
  },
  {
    topic: "Bariatric",
    question: "EGD with deployment of an intragastric bariatric balloon. Which code?",
    correct: "43290",
    wrong: ["43291", "43235, 43290", "43659"],
    explanation: "43290 is EGD with deployment of an intragastric bariatric balloon. 43291 is the removal.",
    lookFor: "Deployment versus removal.",
    eliminate: "43291 is removal. 43235 is packaged into any therapeutic EGD code. 43659 is a laparoscopic unlisted code, and this was done by endoscope.",
  },

  // ---------------- Inguinal hernia ----------------
  {
    topic: "Inguinal hernia",
    question: "An infant born at 35 weeks is repaired at 20 weeks of age for an incarcerated hernia. What is the PCA, and which code applies (initial inguinal)?",
    correct: "PCA 55 weeks, 49496",
    wrong: ["PCA 55 weeks, 49495", "PCA 35 weeks, 49492", "PCA 20 weeks, 49500"],
    explanation: "PCA = 35 + 20 = 55 weeks. That is over 50 weeks PCA and the baby is under 6 months old, so the 49495/49496 tier applies. Incarcerated makes it 49496.",
    lookFor: "Add gestational age to age in weeks. Over 50 and under 6 months = the middle tier.",
    eliminate: "49495 is the reducible code. 49492 is the tier for 50 weeks PCA or less. 49500 is for age 6 months or older.",
  },
  {
    topic: "Inguinal hernia",
    question: "Baby Jones was born at 28 weeks. Four weeks after birth he has a herniorrhaphy for a reducible left inguinal hernia. Which code?",
    correct: "49491",
    wrong: ["49492", "49495", "49491-50"],
    explanation: "PCA = 28 + 4 = 32 weeks, which is 50 weeks PCA or less. That is the first tier, and reducible makes it 49491. It is a single side, so no modifier 50.",
    lookFor: "PCA under 50 weeks and no mention of incarceration.",
    eliminate: "49492 is incarcerated or strangulated. 49495 is the tier for babies over 50 weeks PCA. Modifier 50 is for both sides.",
  },
  {
    topic: "Inguinal hernia",
    question: "A 34-year-old man has an initial inguinal hernia that is easily reducible. It is repaired with mesh. Which code(s)?",
    correct: "49505",
    wrong: ["49505, 49568", "49507", "49520"],
    explanation: "Initial inguinal hernia, age 5 or older, reducible = 49505. Mesh is included and not reported separately.",
    lookFor: "Age tier, initial versus recurrent, and reducible versus incarcerated.",
    eliminate: "49568 (mesh) is deleted and mesh is included anyway. 49507 is incarcerated or strangulated. 49520 is a recurrent hernia.",
  },
  {
    topic: "Inguinal hernia",
    question: "A strangulated initial inguinal hernia is repaired in a baby who is 32 weeks old and was born at 35 weeks. Which code?",
    correct: "49501",
    wrong: ["49496", "49492", "49507"],
    explanation: "PCA only decides the tier for babies still under 6 months old. A baby 32 weeks old is about 7.4 months, so the chronologic tier of 6 months to under 5 years applies. Strangulated makes it 49501.",
    lookFor: "Convert the age to months before you use PCA.",
    eliminate: "49496 and 49492 are for babies under 6 months. 49507 is for age 5 or older.",
  },
  {
    topic: "Inguinal hernia",
    question: "A 50-year-old has a recurrent inguinal hernia that is incarcerated. Which code?",
    correct: "49521",
    wrong: ["49507", "49520", "49525"],
    explanation: "Recurrent inguinal hernias use 49520/49521 at any age. Incarcerated makes it 49521.",
    lookFor: "The word 'recurrent'. It ignores age.",
    eliminate: "49507 is an INITIAL hernia. 49520 is the reducible code. 49525 is a sliding hernia.",
  },
  {
    topic: "Inguinal hernia",
    question: "An adult has an initial SLIDING inguinal hernia that is also incarcerated. Which code?",
    correct: "49507",
    wrong: ["49525", "49505", "49520"],
    explanation: "The sliding code 49525 carries a note: for an incarcerated or strangulated inguinal hernia, use the incarcerated or strangulated codes (49496, 49501, 49507, 49521).",
    lookFor: "Sliding AND incarcerated. The clinical state outranks the sliding code.",
    eliminate: "49525 is for a sliding hernia that is not incarcerated. 49505 is reducible. 49520 is recurrent.",
  },
  {
    topic: "Inguinal hernia",
    question: "An adult has a laparoscopic repair of an initial inguinal hernia. Which code?",
    correct: "49650",
    wrong: ["49505", "49651", "49659"],
    explanation: "Inguinal hernias still have their own laparoscopic codes: 49650 initial, 49651 recurrent.",
    lookFor: "Inguinal AND laparoscopic. The anterior abdominal codes ignore the approach, but inguinal does not.",
    eliminate: "49505 is the open code. 49651 is recurrent. 49659 is an unlisted code and a specific code exists.",
  },
  {
    topic: "Inguinal hernia",
    question: "An adult has an initial bilateral open inguinal hernia repair, both sides reducible. How is it reported?",
    correct: "49505-50",
    wrong: ["49650", "49505, 49505-59", "49591"],
    explanation: "Modifier 50 is used on the unilateral inguinal codes for a bilateral repair.",
    lookFor: "'Bilateral' plus an open inguinal code.",
    eliminate: "49650 is laparoscopic. 59 is for a separate site or session, not the other side. 49591 is an anterior abdominal code.",
  },
  {
    topic: "Femoral hernia",
    question: "A 60-year-old has an initial femoral hernia that is incarcerated. Which code?",
    correct: "49553",
    wrong: ["49550", "49557", "49555"],
    explanation: "Initial femoral is 49550 (reducible) and 49553 (incarcerated or strangulated). It does not depend on age.",
    lookFor: "Femoral has no age split. Only initial versus recurrent, and reducible versus incarcerated.",
    eliminate: "49550 is reducible. 49555 and 49557 are the recurrent pair.",
  },

  // ---------------- Anterior abdominal hernia ----------------
  {
    topic: "Anterior hernia",
    question: "A 70-year-old woman has a laparoscopic repair of an initial ventral hernia. The defect is small (under 3 cm) and reducible. Mesh is placed. Which code?",
    correct: "49591",
    wrong: ["49652", "49591, 49568", "49650"],
    explanation: "Anterior abdominal hernias are reported by total defect size, by ANY approach, mesh included. Under 3 cm, initial, reducible = 49591.",
    lookFor: "Size and clinical state. The approach and mesh do not change the code.",
    eliminate: "49652 is a deleted laparoscopic ventral code. 49568 (mesh) is deleted. 49650 is an inguinal code.",
  },
  {
    topic: "Anterior hernia",
    question: "A recurrent incisional hernia with a 4 cm defect, reducible, is repaired open with mesh. Which code?",
    correct: "49615",
    wrong: ["49593", "49616", "49591"],
    explanation: "Recurrent anterior abdominal hernias are 49613–49618. 3–10 cm and reducible is 49615.",
    lookFor: "Recurrent shifts you to the second block of codes. Then the size row.",
    eliminate: "49593 is the same size but INITIAL. 49616 is the incarcerated version. 49591 is initial and under 3 cm.",
  },
  {
    topic: "Anterior hernia",
    question: "At a first-time repair through the same scar, the surgeon repairs a 2 cm reducible incisional hernia and, 2 cm away, a 4 cm incarcerated incisional hernia. Which code?",
    correct: "49594, once",
    wrong: ["49591 and 49594", "49592", "49593"],
    explanation: "The defects are less than 10 cm apart, so they are measured together: 2 + 2 + 4 = 8 cm, in the 3–10 cm row. When a reducible and an incarcerated hernia are repaired together, the whole repair is reported as incarcerated. That is 49594.",
    lookFor: "Add the defects and the gap between them, then check whether any hernia is incarcerated.",
    eliminate: "Two codes ignore the once-per-session, total-size rule. 49592 is under 3 cm. 49593 is 3–10 cm but reducible.",
  },
  {
    topic: "Anterior hernia",
    question: "A recurrent incisional hernia with a 12 cm defect, incarcerated, is repaired. During the repair the surgeon removes all of the old, non-infected mesh. Which code(s)?",
    correct: "49618, +49623",
    wrong: ["49618", "49618, 11008", "49618, 49568"],
    explanation: "12 cm, recurrent, incarcerated = 49618. Removal of total or near-total non-infected mesh is the add-on +49623.",
    lookFor: "The words 'non-infected mesh removed'. That points to +49623.",
    eliminate: "49618 alone leaves out the mesh removal. 11008 is for INFECTED mesh removal. 49568 is deleted.",
  },
  {
    topic: "Anterior hernia",
    question: "A laparoscopic repair of an initial ventral hernia measuring 5 cm, reducible, with mesh. Which code?",
    correct: "49593",
    wrong: ["49652", "49591, 49568", "49650"],
    explanation: "5 cm falls in the 3–10 cm row. Initial and reducible is 49593. Laparoscopy and mesh are included.",
    lookFor: "Old training material may still show 49652–49657. Those are not in the 2026 codebook.",
    eliminate: "49652 no longer exists. 49568 no longer exists and mesh is included. 49650 is for inguinal hernias.",
  },

  // ---------------- Hemorrhoids ----------------
  {
    topic: "Hemorrhoids",
    question: "A postpartum patient has three external hemorrhoids excised at 5, 7–8, and 10–11 o'clock, spanning at least two columns. Which code?",
    correct: "46250, once",
    wrong: ["46320", "46250, 46320", "46999"],
    explanation: "External hemorrhoidectomy of 2 or more columns/groups is 46250. The thrombosed one is not billed separately by usual convention.",
    lookFor: "Count the COLUMNS treated, not the number of lumps.",
    eliminate: "46320 is for excising one thrombosed external hemorrhoid as the whole procedure. 46999 is for a single column.",
  },
  {
    topic: "Hemorrhoids",
    question: "Rubber band ligation of internal hemorrhoids, done in the office with no scope. Which code?",
    correct: "46221",
    wrong: ["46945", "45350", "46250"],
    explanation: "46221 is internal hemorrhoidectomy by rubber band ligation. With a scope, the scope code (45350 or 45398) is used instead.",
    lookFor: "Did a scope carry the band? No scope means 46221.",
    eliminate: "46945 is a ligation OTHER than a rubber band. 45350 needs a sigmoidoscope. 46250 is an excision.",
  },
  {
    topic: "Hemorrhoids",
    question: "Transanal hemorrhoidal dearterialization (THD) with ultrasound guidance and mucopexy, treating three columns. Which code(s)?",
    correct: "46948",
    wrong: ["46946", "46948, 76942", "46947"],
    explanation: "46948 is THD of 2 or more columns and includes ultrasound guidance and mucopexy when performed. The imaging codes are not added.",
    lookFor: "The name of the technique: dearterialization.",
    eliminate: "46946 is ligation other than THD. 76942 is included in 46948. 46947 is a stapled hemorrhoidopexy.",
  },
  {
    topic: "Hemorrhoids",
    question: "A doctor incises a painful thrombosed external hemorrhoid and drains the clot. The hemorrhoid is not removed. Which code?",
    correct: "46083",
    wrong: ["46320", "46250", "46221"],
    explanation: "46083 is INCISION of a thrombosed external hemorrhoid. Removing it is EXCISION, 46320.",
    lookFor: "Incision (drain the clot) versus excision (cut it out).",
    eliminate: "46320 is excision. 46250 is a multi-column external hemorrhoidectomy. 46221 is a rubber band for internal hemorrhoids.",
  },
  {
    topic: "Hemorrhoids",
    question: "Internal and external hemorrhoidectomy of 3 columns, with a fissurectomy in the same session. Which code?",
    correct: "46261",
    wrong: ["46260", "46257", "46262"],
    explanation: "46260 is internal and external, 2 or more columns. 46261 is the same with fissurectomy. 46262 is with fistulectomy.",
    lookFor: "Column count (2 or more) plus the extra procedure.",
    eliminate: "46260 leaves out the fissurectomy. 46257 is the single-column version. 46262 is the fistulectomy version.",
  },
  {
    topic: "Hemorrhoids",
    question: "An external hemorrhoidectomy of a single column. Which code?",
    correct: "46999",
    wrong: ["46250", "46320", "46255"],
    explanation: "46250 is for 2 or more columns. A single-column external hemorrhoidectomy has no dedicated code and goes to unlisted 46999.",
    lookFor: "'Single column' with an EXTERNAL-only hemorrhoidectomy.",
    eliminate: "46250 needs 2 or more columns. 46320 is for a thrombosed hemorrhoid. 46255 is internal AND external.",
  },
];

export default function DigestivePracticeQuizPage() {
  return (
    <QuizPlayer
      kicker="40,000 SERIES · PRACTICE QUIZ"
      title="Digestive System Practice Quiz"
      blurb={`${items.length} scenario questions across all three reviewer parts — endoscopy rules, esophagoscopy, EGD, enteroscopy, ERCP, sigmoidoscopy, anoscopy, colonoscopy, bariatric, hernia, and hemorrhoids. Every answer is worked out with what to look for and how to eliminate the wrong ones.`}
      nav={[
        { href: "/cpt/surgery/40,000", label: "Digestive home" },
        { href: "/cpt/surgery/40000-series-guidelines-reviewer", label: "Reviewer Part 1" },
        { href: "/cpt/surgery/40000-series-guidelines-reviewer-part-2", label: "Part 2" },
        { href: "/cpt/surgery/40000-series-guidelines-reviewer-part-3", label: "Part 3" },
        { href: "/cpt/surgery/40000-series-flashcards", label: "Flashcards" },
        { href: "/cpt/surgery/40000-series-discussion-guide", label: "Discussion Guide" },
      ]}
      items={items}
    />
  );
}
